name: 'CI'
on:
  push:
  pull_request:
jobs:
  test-job:
    runs-on: self-hosted
    steps:
    
        - name: Check out code
          uses: actions/checkout@v2
    
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: eu-west-2
            
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          
        - name: Add SHORT_SHA env property with commit short sha
          run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          
        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: not-only-yoursactionsforecs
          run: |
              docker build -t $ECR_REGISTRY:$IMAGE_TAG .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
